version: '3'

services:
  rabbitmq-vrp:
    image: rabbitmq:3-management
    container_name: rabbitmq-vrp
    hostname: rabbitmq-vrp
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - shared_network

  tsp-solver-base:
    build:
      dockerfile: Dockerfile
      context: .
    command: bash -c "chmod +x wait-for-it.sh && ./wait-for-it.sh rabbitmq:5672 -- python main.py"
    container_name: tsp-solver-base
    hostname: tsp-solver-base
    volumes:
      - ./:/tsp-solver
    stdin_open: true
    tty: true
    networks:
      - shared_network
    environment:
      - MESSAGE_BROKER=rabbitmq-vrp
    depends_on:
      - rabbitmq-vrp

networks:
  shared_network:
    driver: bridge